# standard object types
user:

identity:
  identifier:

# RAI domain object types
#
# Kludge: We need to define all permissions defined in all child object types at
# the account type level (i.e. top-level) to enable permission inheritance.
account:
  member:

  owner:
    union:
      - contributor
      - reader
    permissions:
      - delete

  contributor:
    union:
      - reader
    permissions:
      - update
      - create_write_transaction

  reader:
    permissions:
      - read
      - create_read_transaction
      - list_transactions

resource_group:
  parent:

  owner:
    union:
      - reader
      - contributor
      - delete
    permissions:
      - read
      - update
      - delete

  contributor:
    union:
      - reader
    permissions:
      - update

  reader:
    union:
    permissions:
      - read

  read:
    permissions:
      - read

  update:
    permissions:
      - update

  delete:
    permissions:
      - delete

database:
  parent:

  owner:
    union:
      - reader
      - contributor
      - delete
    permissions:
      - read
      - create_read_transaction
      - list_transactions
      - update
      - create_write_transaction
      - delete

  contributor:
    union:
      - reader
      - update
      - create_write_transaction
    permissions:
      - read
      - create_read_transaction
      - list_transactions
      - update
      - create_write_transaction

  reader:
    union:
      - read
      - create_read_transaction
      - list_transactions
    permissions:
      - read
      - create_read_transaction
      - list_transactions

  read:
    permissions:
      - read

  create_read_transaction:
    permissions:
      - create_read_transaction

  list_transactions:
    permissions:
      - list_transactions

  update:
    permissions:
      - update

  create_write_transaction:
    permissions:
      - create_write_transaction

  delete:
    permissions:
      - delete

engine:
  parent:

  owner:
    union:
      - contributor
      - reader
      - delete

  contributor:
    union:
      - reader
      - update

  reader:
    union:
      - read

  read:
    permissions:
      - read

  update:
    permissions:
      - update

  delete:
    permissions:
      - delete
