---
model:
  schema_version: 3
  
object_types:
  user:
    relations:
    permissions:
    properties:
      concrete: true

  group:
    relations: 
      member: user
      
  folder:
    relations:
      owner: user
      parent: folder
      viewer: user | user:* | group#member | owner | parent->viewer
    
    permissions:
      can_create_file: owner
  
  doc:
    relations:
      owner: user
      parent: folder
      viewer: user | user:* | group#member

    permissions:
      can_change_owner: owner
      can_share: owner | parent->owner
      can_write: owner & parent->owner
      can_read: viewer | owner | parent->viewer
      can_read_not_write: viewer ! writer
      can_read_not_write2: can_read ! can_write

      can_read_signed: viewer & is_signed_pdf
      can_read_secure: viewer & is_secure_pdf

      is_signed_pdf: $rego:policy.is_signed_pdf
      is_secure_pdf: $wasm:is_secure_pdf
